/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.DataPageItemSchema;
import org.openapitools.client.model.ItemResponseSchema;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ItemsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ItemsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ItemsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getAllItemsItemsGet
     * @param minLevel Minimum level items. (optional)
     * @param maxLevel Maximum level items. (optional)
     * @param name Name of the item. (optional)
     * @param type Type of items. (optional)
     * @param craftSkill Skill to craft items. (optional)
     * @param craftMaterial Item code of items used as material for crafting. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Fetch items details. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Items not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllItemsItemsGetCall(Integer minLevel, Integer maxLevel, String name, String type, String craftSkill, String craftMaterial, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/items/";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (minLevel != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("min_level", minLevel));
        }

        if (maxLevel != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("max_level", maxLevel));
        }

        if (name != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("name", name));
        }

        if (type != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("type", type));
        }

        if (craftSkill != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("craft_skill", craftSkill));
        }

        if (craftMaterial != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("craft_material", craftMaterial));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (size != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("size", size));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAllItemsItemsGetValidateBeforeCall(Integer minLevel, Integer maxLevel, String name, String type, String craftSkill, String craftMaterial, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        return getAllItemsItemsGetCall(minLevel, maxLevel, name, type, craftSkill, craftMaterial, page, size, _callback);

    }

    /**
     * Get All Items
     * Fetch items details.
     * @param minLevel Minimum level items. (optional)
     * @param maxLevel Maximum level items. (optional)
     * @param name Name of the item. (optional)
     * @param type Type of items. (optional)
     * @param craftSkill Skill to craft items. (optional)
     * @param craftMaterial Item code of items used as material for crafting. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return DataPageItemSchema
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Fetch items details. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Items not found. </td><td>  -  </td></tr>
     </table>
     */
    public DataPageItemSchema getAllItemsItemsGet(Integer minLevel, Integer maxLevel, String name, String type, String craftSkill, String craftMaterial, Integer page, Integer size) throws ApiException {
        ApiResponse<DataPageItemSchema> localVarResp = getAllItemsItemsGetWithHttpInfo(minLevel, maxLevel, name, type, craftSkill, craftMaterial, page, size);
        return localVarResp.getData();
    }

    /**
     * Get All Items
     * Fetch items details.
     * @param minLevel Minimum level items. (optional)
     * @param maxLevel Maximum level items. (optional)
     * @param name Name of the item. (optional)
     * @param type Type of items. (optional)
     * @param craftSkill Skill to craft items. (optional)
     * @param craftMaterial Item code of items used as material for crafting. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return ApiResponse&lt;DataPageItemSchema&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Fetch items details. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Items not found. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DataPageItemSchema> getAllItemsItemsGetWithHttpInfo(Integer minLevel, Integer maxLevel, String name, String type, String craftSkill, String craftMaterial, Integer page, Integer size) throws ApiException {
        okhttp3.Call localVarCall = getAllItemsItemsGetValidateBeforeCall(minLevel, maxLevel, name, type, craftSkill, craftMaterial, page, size, null);
        Type localVarReturnType = new TypeToken<DataPageItemSchema>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get All Items (asynchronously)
     * Fetch items details.
     * @param minLevel Minimum level items. (optional)
     * @param maxLevel Maximum level items. (optional)
     * @param name Name of the item. (optional)
     * @param type Type of items. (optional)
     * @param craftSkill Skill to craft items. (optional)
     * @param craftMaterial Item code of items used as material for crafting. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Fetch items details. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Items not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllItemsItemsGetAsync(Integer minLevel, Integer maxLevel, String name, String type, String craftSkill, String craftMaterial, Integer page, Integer size, final ApiCallback<DataPageItemSchema> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAllItemsItemsGetValidateBeforeCall(minLevel, maxLevel, name, type, craftSkill, craftMaterial, page, size, _callback);
        Type localVarReturnType = new TypeToken<DataPageItemSchema>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getItemItemsCodeGet
     * @param code The code of the item. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched item. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Item not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getItemItemsCodeGetCall(String code, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/items/{code}"
            .replace("{" + "code" + "}", localVarApiClient.escapeString(code.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getItemItemsCodeGetValidateBeforeCall(String code, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'code' is set
        if (code == null) {
            throw new ApiException("Missing the required parameter 'code' when calling getItemItemsCodeGet(Async)");
        }

        return getItemItemsCodeGetCall(code, _callback);

    }

    /**
     * Get Item
     * Retrieve the details of a item.
     * @param code The code of the item. (required)
     * @return ItemResponseSchema
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched item. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Item not found. </td><td>  -  </td></tr>
     </table>
     */
    public ItemResponseSchema getItemItemsCodeGet(String code) throws ApiException {
        ApiResponse<ItemResponseSchema> localVarResp = getItemItemsCodeGetWithHttpInfo(code);
        return localVarResp.getData();
    }

    /**
     * Get Item
     * Retrieve the details of a item.
     * @param code The code of the item. (required)
     * @return ApiResponse&lt;ItemResponseSchema&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched item. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Item not found. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ItemResponseSchema> getItemItemsCodeGetWithHttpInfo(String code) throws ApiException {
        okhttp3.Call localVarCall = getItemItemsCodeGetValidateBeforeCall(code, null);
        Type localVarReturnType = new TypeToken<ItemResponseSchema>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Item (asynchronously)
     * Retrieve the details of a item.
     * @param code The code of the item. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched item. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Item not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getItemItemsCodeGetAsync(String code, final ApiCallback<ItemResponseSchema> _callback) throws ApiException {

        okhttp3.Call localVarCall = getItemItemsCodeGetValidateBeforeCall(code, _callback);
        Type localVarReturnType = new TypeToken<ItemResponseSchema>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
