/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.DataPageMonsterSchema;
import org.openapitools.client.model.MonsterResponseSchema;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class MonstersApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public MonstersApi() {
        this(Configuration.getDefaultApiClient());
    }

    public MonstersApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getAllMonstersMonstersGet
     * @param minLevel Monster minimum level. (optional)
     * @param maxLevel Monster maximum level. (optional)
     * @param drop Item code of the drop. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched monsters details. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Monsters not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllMonstersMonstersGetCall(Integer minLevel, Integer maxLevel, String drop, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/monsters/";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (minLevel != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("min_level", minLevel));
        }

        if (maxLevel != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("max_level", maxLevel));
        }

        if (drop != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("drop", drop));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (size != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("size", size));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAllMonstersMonstersGetValidateBeforeCall(Integer minLevel, Integer maxLevel, String drop, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        return getAllMonstersMonstersGetCall(minLevel, maxLevel, drop, page, size, _callback);

    }

    /**
     * Get All Monsters
     * Fetch monsters details.
     * @param minLevel Monster minimum level. (optional)
     * @param maxLevel Monster maximum level. (optional)
     * @param drop Item code of the drop. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return DataPageMonsterSchema
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched monsters details. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Monsters not found. </td><td>  -  </td></tr>
     </table>
     */
    public DataPageMonsterSchema getAllMonstersMonstersGet(Integer minLevel, Integer maxLevel, String drop, Integer page, Integer size) throws ApiException {
        ApiResponse<DataPageMonsterSchema> localVarResp = getAllMonstersMonstersGetWithHttpInfo(minLevel, maxLevel, drop, page, size);
        return localVarResp.getData();
    }

    /**
     * Get All Monsters
     * Fetch monsters details.
     * @param minLevel Monster minimum level. (optional)
     * @param maxLevel Monster maximum level. (optional)
     * @param drop Item code of the drop. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return ApiResponse&lt;DataPageMonsterSchema&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched monsters details. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Monsters not found. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DataPageMonsterSchema> getAllMonstersMonstersGetWithHttpInfo(Integer minLevel, Integer maxLevel, String drop, Integer page, Integer size) throws ApiException {
        okhttp3.Call localVarCall = getAllMonstersMonstersGetValidateBeforeCall(minLevel, maxLevel, drop, page, size, null);
        Type localVarReturnType = new TypeToken<DataPageMonsterSchema>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get All Monsters (asynchronously)
     * Fetch monsters details.
     * @param minLevel Monster minimum level. (optional)
     * @param maxLevel Monster maximum level. (optional)
     * @param drop Item code of the drop. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched monsters details. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Monsters not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllMonstersMonstersGetAsync(Integer minLevel, Integer maxLevel, String drop, Integer page, Integer size, final ApiCallback<DataPageMonsterSchema> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAllMonstersMonstersGetValidateBeforeCall(minLevel, maxLevel, drop, page, size, _callback);
        Type localVarReturnType = new TypeToken<DataPageMonsterSchema>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getMonsterMonstersCodeGet
     * @param code The code of the monster. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched monster. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Monster not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getMonsterMonstersCodeGetCall(String code, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/monsters/{code}"
            .replace("{" + "code" + "}", localVarApiClient.escapeString(code.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getMonsterMonstersCodeGetValidateBeforeCall(String code, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'code' is set
        if (code == null) {
            throw new ApiException("Missing the required parameter 'code' when calling getMonsterMonstersCodeGet(Async)");
        }

        return getMonsterMonstersCodeGetCall(code, _callback);

    }

    /**
     * Get Monster
     * Retrieve the details of a monster.
     * @param code The code of the monster. (required)
     * @return MonsterResponseSchema
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched monster. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Monster not found. </td><td>  -  </td></tr>
     </table>
     */
    public MonsterResponseSchema getMonsterMonstersCodeGet(String code) throws ApiException {
        ApiResponse<MonsterResponseSchema> localVarResp = getMonsterMonstersCodeGetWithHttpInfo(code);
        return localVarResp.getData();
    }

    /**
     * Get Monster
     * Retrieve the details of a monster.
     * @param code The code of the monster. (required)
     * @return ApiResponse&lt;MonsterResponseSchema&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched monster. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Monster not found. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<MonsterResponseSchema> getMonsterMonstersCodeGetWithHttpInfo(String code) throws ApiException {
        okhttp3.Call localVarCall = getMonsterMonstersCodeGetValidateBeforeCall(code, null);
        Type localVarReturnType = new TypeToken<MonsterResponseSchema>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Monster (asynchronously)
     * Retrieve the details of a monster.
     * @param code The code of the monster. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched monster. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Monster not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getMonsterMonstersCodeGetAsync(String code, final ApiCallback<MonsterResponseSchema> _callback) throws ApiException {

        okhttp3.Call localVarCall = getMonsterMonstersCodeGetValidateBeforeCall(code, _callback);
        Type localVarReturnType = new TypeToken<MonsterResponseSchema>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
