/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.DataPageResourceSchema;
import org.openapitools.client.model.ResourceResponseSchema;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ResourcesApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ResourcesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ResourcesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getAllResourcesResourcesGet
     * @param minLevel Skill minimum level. (optional)
     * @param maxLevel Skill maximum level. (optional)
     * @param skill The code of the skill. (optional)
     * @param drop Item code of the drop. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched resources details. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resources not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllResourcesResourcesGetCall(Integer minLevel, Integer maxLevel, String skill, String drop, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/resources/";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (minLevel != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("min_level", minLevel));
        }

        if (maxLevel != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("max_level", maxLevel));
        }

        if (skill != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("skill", skill));
        }

        if (drop != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("drop", drop));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (size != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("size", size));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getAllResourcesResourcesGetValidateBeforeCall(Integer minLevel, Integer maxLevel, String skill, String drop, Integer page, Integer size, final ApiCallback _callback) throws ApiException {
        return getAllResourcesResourcesGetCall(minLevel, maxLevel, skill, drop, page, size, _callback);

    }

    /**
     * Get All Resources
     * Fetch resources details.
     * @param minLevel Skill minimum level. (optional)
     * @param maxLevel Skill maximum level. (optional)
     * @param skill The code of the skill. (optional)
     * @param drop Item code of the drop. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return DataPageResourceSchema
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched resources details. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resources not found. </td><td>  -  </td></tr>
     </table>
     */
    public DataPageResourceSchema getAllResourcesResourcesGet(Integer minLevel, Integer maxLevel, String skill, String drop, Integer page, Integer size) throws ApiException {
        ApiResponse<DataPageResourceSchema> localVarResp = getAllResourcesResourcesGetWithHttpInfo(minLevel, maxLevel, skill, drop, page, size);
        return localVarResp.getData();
    }

    /**
     * Get All Resources
     * Fetch resources details.
     * @param minLevel Skill minimum level. (optional)
     * @param maxLevel Skill maximum level. (optional)
     * @param skill The code of the skill. (optional)
     * @param drop Item code of the drop. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @return ApiResponse&lt;DataPageResourceSchema&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched resources details. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resources not found. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DataPageResourceSchema> getAllResourcesResourcesGetWithHttpInfo(Integer minLevel, Integer maxLevel, String skill, String drop, Integer page, Integer size) throws ApiException {
        okhttp3.Call localVarCall = getAllResourcesResourcesGetValidateBeforeCall(minLevel, maxLevel, skill, drop, page, size, null);
        Type localVarReturnType = new TypeToken<DataPageResourceSchema>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get All Resources (asynchronously)
     * Fetch resources details.
     * @param minLevel Skill minimum level. (optional)
     * @param maxLevel Skill maximum level. (optional)
     * @param skill The code of the skill. (optional)
     * @param drop Item code of the drop. (optional)
     * @param page Page number (optional, default to 1)
     * @param size Page size (optional, default to 50)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched resources details. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resources not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getAllResourcesResourcesGetAsync(Integer minLevel, Integer maxLevel, String skill, String drop, Integer page, Integer size, final ApiCallback<DataPageResourceSchema> _callback) throws ApiException {

        okhttp3.Call localVarCall = getAllResourcesResourcesGetValidateBeforeCall(minLevel, maxLevel, skill, drop, page, size, _callback);
        Type localVarReturnType = new TypeToken<DataPageResourceSchema>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getResourceResourcesCodeGet
     * @param code The code of the resource. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getResourceResourcesCodeGetCall(String code, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/resources/{code}"
            .replace("{" + "code" + "}", localVarApiClient.escapeString(code.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getResourceResourcesCodeGetValidateBeforeCall(String code, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'code' is set
        if (code == null) {
            throw new ApiException("Missing the required parameter 'code' when calling getResourceResourcesCodeGet(Async)");
        }

        return getResourceResourcesCodeGetCall(code, _callback);

    }

    /**
     * Get Resource
     * Retrieve the details of a resource.
     * @param code The code of the resource. (required)
     * @return ResourceResponseSchema
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource not found. </td><td>  -  </td></tr>
     </table>
     */
    public ResourceResponseSchema getResourceResourcesCodeGet(String code) throws ApiException {
        ApiResponse<ResourceResponseSchema> localVarResp = getResourceResourcesCodeGetWithHttpInfo(code);
        return localVarResp.getData();
    }

    /**
     * Get Resource
     * Retrieve the details of a resource.
     * @param code The code of the resource. (required)
     * @return ApiResponse&lt;ResourceResponseSchema&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource not found. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ResourceResponseSchema> getResourceResourcesCodeGetWithHttpInfo(String code) throws ApiException {
        okhttp3.Call localVarCall = getResourceResourcesCodeGetValidateBeforeCall(code, null);
        Type localVarReturnType = new TypeToken<ResourceResponseSchema>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get Resource (asynchronously)
     * Retrieve the details of a resource.
     * @param code The code of the resource. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successfully fetched resource. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource not found. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getResourceResourcesCodeGetAsync(String code, final ApiCallback<ResourceResponseSchema> _callback) throws ApiException {

        okhttp3.Call localVarCall = getResourceResourcesCodeGetValidateBeforeCall(code, _callback);
        Type localVarReturnType = new TypeToken<ResourceResponseSchema>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
