/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BlockedHitsSchema
 */
public class BlockedHitsSchemaTest {
    private final BlockedHitsSchema model = new BlockedHitsSchema();

    /**
     * Model tests for BlockedHitsSchema
     */
    @Test
    public void testBlockedHitsSchema() {
        // TODO: test BlockedHitsSchema
    }

    /**
     * Test the property 'fire'
     */
    @Test
    public void fireTest() {
        // TODO: test fire
    }

    /**
     * Test the property 'earth'
     */
    @Test
    public void earthTest() {
        // TODO: test earth
    }

    /**
     * Test the property 'water'
     */
    @Test
    public void waterTest() {
        // TODO: test water
    }

    /**
     * Test the property 'air'
     */
    @Test
    public void airTest() {
        // TODO: test air
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

}
