/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.InventorySlot;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CharacterSchema
 */
public class CharacterSchemaTest {
    private final CharacterSchema model = new CharacterSchema();

    /**
     * Model tests for CharacterSchema
     */
    @Test
    public void testCharacterSchema() {
        // TODO: test CharacterSchema
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'skin'
     */
    @Test
    public void skinTest() {
        // TODO: test skin
    }

    /**
     * Test the property 'level'
     */
    @Test
    public void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'xp'
     */
    @Test
    public void xpTest() {
        // TODO: test xp
    }

    /**
     * Test the property 'maxXp'
     */
    @Test
    public void maxXpTest() {
        // TODO: test maxXp
    }

    /**
     * Test the property 'totalXp'
     */
    @Test
    public void totalXpTest() {
        // TODO: test totalXp
    }

    /**
     * Test the property 'gold'
     */
    @Test
    public void goldTest() {
        // TODO: test gold
    }

    /**
     * Test the property 'speed'
     */
    @Test
    public void speedTest() {
        // TODO: test speed
    }

    /**
     * Test the property 'miningLevel'
     */
    @Test
    public void miningLevelTest() {
        // TODO: test miningLevel
    }

    /**
     * Test the property 'miningXp'
     */
    @Test
    public void miningXpTest() {
        // TODO: test miningXp
    }

    /**
     * Test the property 'miningMaxXp'
     */
    @Test
    public void miningMaxXpTest() {
        // TODO: test miningMaxXp
    }

    /**
     * Test the property 'woodcuttingLevel'
     */
    @Test
    public void woodcuttingLevelTest() {
        // TODO: test woodcuttingLevel
    }

    /**
     * Test the property 'woodcuttingXp'
     */
    @Test
    public void woodcuttingXpTest() {
        // TODO: test woodcuttingXp
    }

    /**
     * Test the property 'woodcuttingMaxXp'
     */
    @Test
    public void woodcuttingMaxXpTest() {
        // TODO: test woodcuttingMaxXp
    }

    /**
     * Test the property 'fishingLevel'
     */
    @Test
    public void fishingLevelTest() {
        // TODO: test fishingLevel
    }

    /**
     * Test the property 'fishingXp'
     */
    @Test
    public void fishingXpTest() {
        // TODO: test fishingXp
    }

    /**
     * Test the property 'fishingMaxXp'
     */
    @Test
    public void fishingMaxXpTest() {
        // TODO: test fishingMaxXp
    }

    /**
     * Test the property 'weaponcraftingLevel'
     */
    @Test
    public void weaponcraftingLevelTest() {
        // TODO: test weaponcraftingLevel
    }

    /**
     * Test the property 'weaponcraftingXp'
     */
    @Test
    public void weaponcraftingXpTest() {
        // TODO: test weaponcraftingXp
    }

    /**
     * Test the property 'weaponcraftingMaxXp'
     */
    @Test
    public void weaponcraftingMaxXpTest() {
        // TODO: test weaponcraftingMaxXp
    }

    /**
     * Test the property 'gearcraftingLevel'
     */
    @Test
    public void gearcraftingLevelTest() {
        // TODO: test gearcraftingLevel
    }

    /**
     * Test the property 'gearcraftingXp'
     */
    @Test
    public void gearcraftingXpTest() {
        // TODO: test gearcraftingXp
    }

    /**
     * Test the property 'gearcraftingMaxXp'
     */
    @Test
    public void gearcraftingMaxXpTest() {
        // TODO: test gearcraftingMaxXp
    }

    /**
     * Test the property 'jewelrycraftingLevel'
     */
    @Test
    public void jewelrycraftingLevelTest() {
        // TODO: test jewelrycraftingLevel
    }

    /**
     * Test the property 'jewelrycraftingXp'
     */
    @Test
    public void jewelrycraftingXpTest() {
        // TODO: test jewelrycraftingXp
    }

    /**
     * Test the property 'jewelrycraftingMaxXp'
     */
    @Test
    public void jewelrycraftingMaxXpTest() {
        // TODO: test jewelrycraftingMaxXp
    }

    /**
     * Test the property 'cookingLevel'
     */
    @Test
    public void cookingLevelTest() {
        // TODO: test cookingLevel
    }

    /**
     * Test the property 'cookingXp'
     */
    @Test
    public void cookingXpTest() {
        // TODO: test cookingXp
    }

    /**
     * Test the property 'cookingMaxXp'
     */
    @Test
    public void cookingMaxXpTest() {
        // TODO: test cookingMaxXp
    }

    /**
     * Test the property 'hp'
     */
    @Test
    public void hpTest() {
        // TODO: test hp
    }

    /**
     * Test the property 'haste'
     */
    @Test
    public void hasteTest() {
        // TODO: test haste
    }

    /**
     * Test the property 'criticalStrike'
     */
    @Test
    public void criticalStrikeTest() {
        // TODO: test criticalStrike
    }

    /**
     * Test the property 'stamina'
     */
    @Test
    public void staminaTest() {
        // TODO: test stamina
    }

    /**
     * Test the property 'attackFire'
     */
    @Test
    public void attackFireTest() {
        // TODO: test attackFire
    }

    /**
     * Test the property 'attackEarth'
     */
    @Test
    public void attackEarthTest() {
        // TODO: test attackEarth
    }

    /**
     * Test the property 'attackWater'
     */
    @Test
    public void attackWaterTest() {
        // TODO: test attackWater
    }

    /**
     * Test the property 'attackAir'
     */
    @Test
    public void attackAirTest() {
        // TODO: test attackAir
    }

    /**
     * Test the property 'dmgFire'
     */
    @Test
    public void dmgFireTest() {
        // TODO: test dmgFire
    }

    /**
     * Test the property 'dmgEarth'
     */
    @Test
    public void dmgEarthTest() {
        // TODO: test dmgEarth
    }

    /**
     * Test the property 'dmgWater'
     */
    @Test
    public void dmgWaterTest() {
        // TODO: test dmgWater
    }

    /**
     * Test the property 'dmgAir'
     */
    @Test
    public void dmgAirTest() {
        // TODO: test dmgAir
    }

    /**
     * Test the property 'resFire'
     */
    @Test
    public void resFireTest() {
        // TODO: test resFire
    }

    /**
     * Test the property 'resEarth'
     */
    @Test
    public void resEarthTest() {
        // TODO: test resEarth
    }

    /**
     * Test the property 'resWater'
     */
    @Test
    public void resWaterTest() {
        // TODO: test resWater
    }

    /**
     * Test the property 'resAir'
     */
    @Test
    public void resAirTest() {
        // TODO: test resAir
    }

    /**
     * Test the property 'x'
     */
    @Test
    public void xTest() {
        // TODO: test x
    }

    /**
     * Test the property 'y'
     */
    @Test
    public void yTest() {
        // TODO: test y
    }

    /**
     * Test the property 'cooldown'
     */
    @Test
    public void cooldownTest() {
        // TODO: test cooldown
    }

    /**
     * Test the property 'cooldownExpiration'
     */
    @Test
    public void cooldownExpirationTest() {
        // TODO: test cooldownExpiration
    }

    /**
     * Test the property 'weaponSlot'
     */
    @Test
    public void weaponSlotTest() {
        // TODO: test weaponSlot
    }

    /**
     * Test the property 'shieldSlot'
     */
    @Test
    public void shieldSlotTest() {
        // TODO: test shieldSlot
    }

    /**
     * Test the property 'helmetSlot'
     */
    @Test
    public void helmetSlotTest() {
        // TODO: test helmetSlot
    }

    /**
     * Test the property 'bodyArmorSlot'
     */
    @Test
    public void bodyArmorSlotTest() {
        // TODO: test bodyArmorSlot
    }

    /**
     * Test the property 'legArmorSlot'
     */
    @Test
    public void legArmorSlotTest() {
        // TODO: test legArmorSlot
    }

    /**
     * Test the property 'bootsSlot'
     */
    @Test
    public void bootsSlotTest() {
        // TODO: test bootsSlot
    }

    /**
     * Test the property 'ring1Slot'
     */
    @Test
    public void ring1SlotTest() {
        // TODO: test ring1Slot
    }

    /**
     * Test the property 'ring2Slot'
     */
    @Test
    public void ring2SlotTest() {
        // TODO: test ring2Slot
    }

    /**
     * Test the property 'amuletSlot'
     */
    @Test
    public void amuletSlotTest() {
        // TODO: test amuletSlot
    }

    /**
     * Test the property 'artifact1Slot'
     */
    @Test
    public void artifact1SlotTest() {
        // TODO: test artifact1Slot
    }

    /**
     * Test the property 'artifact2Slot'
     */
    @Test
    public void artifact2SlotTest() {
        // TODO: test artifact2Slot
    }

    /**
     * Test the property 'artifact3Slot'
     */
    @Test
    public void artifact3SlotTest() {
        // TODO: test artifact3Slot
    }

    /**
     * Test the property 'consumable1Slot'
     */
    @Test
    public void consumable1SlotTest() {
        // TODO: test consumable1Slot
    }

    /**
     * Test the property 'consumable1SlotQuantity'
     */
    @Test
    public void consumable1SlotQuantityTest() {
        // TODO: test consumable1SlotQuantity
    }

    /**
     * Test the property 'consumable2Slot'
     */
    @Test
    public void consumable2SlotTest() {
        // TODO: test consumable2Slot
    }

    /**
     * Test the property 'consumable2SlotQuantity'
     */
    @Test
    public void consumable2SlotQuantityTest() {
        // TODO: test consumable2SlotQuantity
    }

    /**
     * Test the property 'task'
     */
    @Test
    public void taskTest() {
        // TODO: test task
    }

    /**
     * Test the property 'taskType'
     */
    @Test
    public void taskTypeTest() {
        // TODO: test taskType
    }

    /**
     * Test the property 'taskProgress'
     */
    @Test
    public void taskProgressTest() {
        // TODO: test taskProgress
    }

    /**
     * Test the property 'taskTotal'
     */
    @Test
    public void taskTotalTest() {
        // TODO: test taskTotal
    }

    /**
     * Test the property 'inventoryMaxItems'
     */
    @Test
    public void inventoryMaxItemsTest() {
        // TODO: test inventoryMaxItems
    }

    /**
     * Test the property 'inventory'
     */
    @Test
    public void inventoryTest() {
        // TODO: test inventory
    }

}
