/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.BlockedHitsSchema;
import org.openapitools.client.model.DropSchema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FightSchema
 */
public class FightSchemaTest {
    private final FightSchema model = new FightSchema();

    /**
     * Model tests for FightSchema
     */
    @Test
    public void testFightSchema() {
        // TODO: test FightSchema
    }

    /**
     * Test the property 'xp'
     */
    @Test
    public void xpTest() {
        // TODO: test xp
    }

    /**
     * Test the property 'gold'
     */
    @Test
    public void goldTest() {
        // TODO: test gold
    }

    /**
     * Test the property 'drops'
     */
    @Test
    public void dropsTest() {
        // TODO: test drops
    }

    /**
     * Test the property 'turns'
     */
    @Test
    public void turnsTest() {
        // TODO: test turns
    }

    /**
     * Test the property 'monsterBlockedHits'
     */
    @Test
    public void monsterBlockedHitsTest() {
        // TODO: test monsterBlockedHits
    }

    /**
     * Test the property 'playerBlockedHits'
     */
    @Test
    public void playerBlockedHitsTest() {
        // TODO: test playerBlockedHits
    }

    /**
     * Test the property 'logs'
     */
    @Test
    public void logsTest() {
        // TODO: test logs
    }

    /**
     * Test the property 'result'
     */
    @Test
    public void resultTest() {
        // TODO: test result
    }

}
