/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GEItemSchema
 */
public class GEItemSchemaTest {
    private final GEItemSchema model = new GEItemSchema();

    /**
     * Model tests for GEItemSchema
     */
    @Test
    public void testGEItemSchema() {
        // TODO: test GEItemSchema
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'stock'
     */
    @Test
    public void stockTest() {
        // TODO: test stock
    }

    /**
     * Test the property 'sellPrice'
     */
    @Test
    public void sellPriceTest() {
        // TODO: test sellPrice
    }

    /**
     * Test the property 'buyPrice'
     */
    @Test
    public void buyPriceTest() {
        // TODO: test buyPrice
    }

}
