/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.DropRateSchema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MonsterSchema
 */
public class MonsterSchemaTest {
    private final MonsterSchema model = new MonsterSchema();

    /**
     * Model tests for MonsterSchema
     */
    @Test
    public void testMonsterSchema() {
        // TODO: test MonsterSchema
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'level'
     */
    @Test
    public void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'hp'
     */
    @Test
    public void hpTest() {
        // TODO: test hp
    }

    /**
     * Test the property 'attackFire'
     */
    @Test
    public void attackFireTest() {
        // TODO: test attackFire
    }

    /**
     * Test the property 'attackEarth'
     */
    @Test
    public void attackEarthTest() {
        // TODO: test attackEarth
    }

    /**
     * Test the property 'attackWater'
     */
    @Test
    public void attackWaterTest() {
        // TODO: test attackWater
    }

    /**
     * Test the property 'attackAir'
     */
    @Test
    public void attackAirTest() {
        // TODO: test attackAir
    }

    /**
     * Test the property 'resFire'
     */
    @Test
    public void resFireTest() {
        // TODO: test resFire
    }

    /**
     * Test the property 'resEarth'
     */
    @Test
    public void resEarthTest() {
        // TODO: test resEarth
    }

    /**
     * Test the property 'resWater'
     */
    @Test
    public void resWaterTest() {
        // TODO: test resWater
    }

    /**
     * Test the property 'resAir'
     */
    @Test
    public void resAirTest() {
        // TODO: test resAir
    }

    /**
     * Test the property 'minGold'
     */
    @Test
    public void minGoldTest() {
        // TODO: test minGold
    }

    /**
     * Test the property 'maxGold'
     */
    @Test
    public void maxGoldTest() {
        // TODO: test maxGold
    }

    /**
     * Test the property 'drops'
     */
    @Test
    public void dropsTest() {
        // TODO: test drops
    }

}
