/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AnnouncementSchema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StatusSchema
 */
public class StatusSchemaTest {
    private final StatusSchema model = new StatusSchema();

    /**
     * Model tests for StatusSchema
     */
    @Test
    public void testStatusSchema() {
        // TODO: test StatusSchema
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'charactersOnline'
     */
    @Test
    public void charactersOnlineTest() {
        // TODO: test charactersOnline
    }

    /**
     * Test the property 'serverTime'
     */
    @Test
    public void serverTimeTest() {
        // TODO: test serverTime
    }

    /**
     * Test the property 'announcements'
     */
    @Test
    public void announcementsTest() {
        // TODO: test announcements
    }

    /**
     * Test the property 'lastWipe'
     */
    @Test
    public void lastWipeTest() {
        // TODO: test lastWipe
    }

    /**
     * Test the property 'nextWipe'
     */
    @Test
    public void nextWipeTest() {
        // TODO: test nextWipe
    }

}
