/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ValidationErrorLocInner
 */
public class ValidationErrorLocInnerTest {
    private final ValidationErrorLocInner model = new ValidationErrorLocInner();

    /**
     * Model tests for ValidationErrorLocInner
     */
    @Test
    public void testValidationErrorLocInner() {
        // TODO: test ValidationErrorLocInner
    }

}
