/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * UnequipSchema
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-09T17:40:21.793932300+10:00[Australia/Sydney]", comments = "Generator version: 7.6.0")
public class UnequipSchema {
  /**
   * Item slot.
   */
  @JsonAdapter(SlotEnum.Adapter.class)
  public enum SlotEnum {
    WEAPON("weapon"),
    
    SHIELD("shield"),
    
    HELMET("helmet"),
    
    BODY_ARMOR("body_armor"),
    
    LEG_ARMOR("leg_armor"),
    
    BOOTS("boots"),
    
    RING1("ring1"),
    
    RING2("ring2"),
    
    AMULET("amulet"),
    
    ARTIFACT1("artifact1"),
    
    ARTIFACT2("artifact2"),
    
    ARTIFACT3("artifact3"),
    
    CONSUMABLE1("consumable1"),
    
    CONSUMABLE2("consumable2");

    private String value;

    SlotEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SlotEnum fromValue(String value) {
      for (SlotEnum b : SlotEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SlotEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SlotEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SlotEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SlotEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      SlotEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_SLOT = "slot";
  @SerializedName(SERIALIZED_NAME_SLOT)
  private SlotEnum slot;

  public UnequipSchema() {
  }

  public UnequipSchema slot(SlotEnum slot) {
    this.slot = slot;
    return this;
  }

   /**
   * Item slot.
   * @return slot
  **/
  @javax.annotation.Nonnull
  public SlotEnum getSlot() {
    return slot;
  }

  public void setSlot(SlotEnum slot) {
    this.slot = slot;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnequipSchema unequipSchema = (UnequipSchema) o;
    return Objects.equals(this.slot, unequipSchema.slot);
  }

  @Override
  public int hashCode() {
    return Objects.hash(slot);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnequipSchema {\n");
    sb.append("    slot: ").append(toIndentedString(slot)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("slot");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("slot");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to UnequipSchema
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UnequipSchema.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UnequipSchema is not found in the empty JSON string", UnequipSchema.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UnequipSchema.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UnequipSchema` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UnequipSchema.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("slot").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `slot` to be a primitive type in the JSON string but got `%s`", jsonObj.get("slot").toString()));
      }
      // validate the required field `slot`
      SlotEnum.validateJsonElement(jsonObj.get("slot"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UnequipSchema.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UnequipSchema' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UnequipSchema> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UnequipSchema.class));

       return (TypeAdapter<T>) new TypeAdapter<UnequipSchema>() {
           @Override
           public void write(JsonWriter out, UnequipSchema value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UnequipSchema read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UnequipSchema given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UnequipSchema
  * @throws IOException if the JSON string is invalid with respect to UnequipSchema
  */
  public static UnequipSchema fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UnequipSchema.class);
  }

 /**
  * Convert an instance of UnequipSchema to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

