/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.DataPageGEItemSchema;
import org.openapitools.client.model.GEItemResponseSchema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GrandExchangeApi
 */
@Disabled
public class GrandExchangeApiTest {

    private final GrandExchangeApi api = new GrandExchangeApi();

    /**
     * Get All Ge Items
     *
     * Fetch Grand Exchange items details.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllGeItemsGeGetTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        DataPageGEItemSchema response = api.getAllGeItemsGeGet(page, size);
        // TODO: test validations
    }

    /**
     * Get Ge Item
     *
     * Retrieve the details of a Grand Exchange item.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getGeItemGeCodeGetTest() throws ApiException {
        String code = null;
        GEItemResponseSchema response = api.getGeItemGeCodeGet(code);
        // TODO: test validations
    }

}
