/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ChangePassword;
import org.openapitools.client.model.DataPageSimpleItemSchema;
import org.openapitools.client.model.GoldBankResponseSchema;
import org.openapitools.client.model.ResponseSchema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MyAccountApi
 */
@Disabled
public class MyAccountApiTest {

    private final MyAccountApi api = new MyAccountApi();

    /**
     * Change Password
     *
     * Change your account password. Changing the password reset the account token.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void changePasswordMyChangePasswordPostTest() throws ApiException {
        ChangePassword changePassword = null;
        ResponseSchema response = api.changePasswordMyChangePasswordPost(changePassword);
        // TODO: test validations
    }

    /**
     * Get Bank Golds
     *
     * Fetch golds in your bank.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBankGoldsMyBankGoldGetTest() throws ApiException {
        GoldBankResponseSchema response = api.getBankGoldsMyBankGoldGet();
        // TODO: test validations
    }

    /**
     * Get Bank Items
     *
     * Fetch all items in your bank.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getBankItemsMyBankItemsGetTest() throws ApiException {
        String itemCode = null;
        Integer page = null;
        Integer size = null;
        DataPageSimpleItemSchema response = api.getBankItemsMyBankItemsGet(itemCode, page, size);
        // TODO: test validations
    }

}
