/*
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.DataPageResourceSchema;
import org.openapitools.client.model.ResourceResponseSchema;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ResourcesApi
 */
@Disabled
public class ResourcesApiTest {

    private final ResourcesApi api = new ResourcesApi();

    /**
     * Get All Resources
     *
     * Fetch resources details.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllResourcesResourcesGetTest() throws ApiException {
        Integer minLevel = null;
        Integer maxLevel = null;
        String skill = null;
        String drop = null;
        Integer page = null;
        Integer size = null;
        DataPageResourceSchema response = api.getAllResourcesResourcesGet(minLevel, maxLevel, skill, drop, page, size);
        // TODO: test validations
    }

    /**
     * Get Resource
     *
     * Retrieve the details of a resource.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getResourceResourcesCodeGetTest() throws ApiException {
        String code = null;
        ResourceResponseSchema response = api.getResourceResourcesCodeGet(code);
        // TODO: test validations
    }

}
